# 第四周学习总结

## Python入门

    
   这周总结的知识点多且重要，是用python进行数据分析的核心知识之一了。学习4个Lessons：Lesson7脚本编写、Lesson8 NumPy、Lesson9 Pandas、Lesson10进阶知识（迭代器和生成器），还有几个补充的知识点以及汇合了《利用python进行数据分析》这本书的一些知识点。

### 【要注意的点】

### Lesson 7脚本编写

**1、安装Pyhton**

不论电脑中有没有安装Python,都可以安装实用的[Anaconda](https://www.anaconda.com/distribution/#download-section)。Anaconda类似于Python的pip，但用途更广一些，可以提供不同的packages和虚拟环境，可以切换环境、包，是一个针对数据分析的管理平台，使用Anaconda prompt可以运行Python命令行，连带的Jupyter notebook(即IPython notebook，可迭代测试试调)外加一个文本编辑器(如Atom)，是今后数据分析的重要组合工具。

__知识扩展__

__①SHELL__

在Windows系统中要运行shell终端，可以下载git,使用具有Unix风格的shell——git bash.

了解了与系统交互的基本操作命令和文件处理等命令，未与数据分析运用挂钩，不详述。

__②Anaconda and Jupyter notebook.__

了解了在Anaconda prompt中与python相关的如创建环境等基本命令，不详述。

了解了在数据分析中使用Jupyter notebook的便利性及其具体使用方法，从打开到各个模块的编辑到文件保存等过程，TAB补全、内省“？”、%run命令、Markdown语法、快捷键的使用以及魔法命令等的使用都很重要，需要积累和经常使用，能大大增加效率。               

__2、运行python__

介绍了使用git bash运行python的方式，这适合习惯使用shell的同学；也可直接在ananconda prompt中运行pytho；

介绍了在命令行中脚本的运行（.py文件）以及使用文本编辑器（如atom）；

__3、python的脚本内容__

`input`（用户输入）的学习；

**4、错误和处理错误**

在python脚本执行时，错误可大致分为两类：语法错误和异常。要学会阅读错误提示和灵活运用搜索引擎进行错误解决。

使用try语句处理异常，这样可以使代码不至于奔溃,可以使用try语句来自定义函数，使某些语句运行失败时可以优雅地返回。

```
try:  
except:    
else:   
finally:```

在IPython中用%run执行一个脚本或任何语句报错时，IPython都会默认打印出完整的报错追溯，可灵活运用魔术命令来差错调试。

在处理异常时还可结合try语句和as访问错误。

**5、在python中读取文件**

使用open函数来选择读或写文件（可通过参数"r"',"w"选择）。使用read方法来访问文件内容。使用close方法来关闭文件，释放文件占用的空间。使用with关键字来自动关闭文件。

**6、导入脚本**

脚本的导入和python模块、包的导入类似，目的就是重复运用脚本中已经编写好的代码、函数等，简化整体代码，所以都可以用点记法。

`import useful_functions.py as uf`

使用if main 块来避免运行从其他脚本中作为模块导入的可执行语句（也就是声明那些代码只在本脚本作为主脚本时可运行）。

**7、模块、包**

__①标准库__

python内置了很多有用的函数、方法，分装在各个模块中，也称为标准库。用import语句导入。

__②第三方库__

第三方库很多，数据分析常用的如numpy,pandas等，先安装包（install），再导入。

**8、在线资源**

学会阅读文档，充分利用网络资源。

### LESSON 8 NumPy

__1、NumPy简介__

NumPy的最大特点的内容是ndarray，即一种高效多维数组。多维数组的快速向量化计算也是重要特点之一。虽然NumPy提供了数值数据操作的计算基础，但大多数读者还是把Pandas作为统计、分析的基石。虽然深入理解NumPy对于大部分数据分析应用并不是必需的，但是精通基于数组的编程和思考是成为Python科学计算专家的重要一步，也是Pandas的基础。

__2、创建 ndarray__

可以通过多种方式创建ndarray。


__①使用普通的列表（序列）和array函数创建__

即使用array函数。array函数接收任意的序列型对象（也包括其他的数组），生成新的包含传递数据的NumPy数组。dtype指定数据类型，否则默认。

In [2]:
import numpy as np
data1=[[1,2,3],[4,5,6],[7,8,9],[10,11,12]]
X=np.array(data1,dtype=np.int64)
print(X)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


__②使用内置函数创建__

__⑴使用range(或linspace)函数和reshape方法（也可作为函数）创建__

arange是内建函数range的数组版,linshape按隔断数划分，区间默认[ ],endpoint=False表示[ )。

In [3]:
X=np.arange(1,47,3)
X=np.reshape(X,(4,4))
print(X)

[[ 1  4  7 10]
 [13 16 19 22]
 [25 28 31 34]
 [37 40 43 46]]


In [5]:
Y=np.arange(1,47,3).reshape(4,4)
print(Y)

[[ 1  4  7 10]
 [13 16 19 22]
 [25 28 31 34]
 [37 40 43 46]]


In [7]:
Z=np.linspace(0,25,10,endpoint=False).reshape(2,5)
print(Z)

[[ 0.   2.5  5.   7.5 10. ]
 [12.5 15.  17.5 20.  22.5]]


__⑵特殊的数组函数__

In [10]:
#元素全是0的数组
X=np.zeros((3,4))
print(X)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [12]:
#元素全是1的数组
Y=np.ones((3,2))
print(Y)

[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [14]:
#元素全是指定数字的数组
Z=np.full((2,3),5)
print(Z)

[[5 5 5]
 [5 5 5]]


In [15]:
#单位矩阵
S=np.eye(5)
print(S)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [16]:
#对角矩阵
T=np.diag([10,20,30,50])
print(T)

[[10  0  0  0]
 [ 0 20  0  0]
 [ 0  0 30  0]
 [ 0  0  0 50]]


__⑶随机数组__

In [18]:
#随机值范围为[0.0,1.0)
X=np.random.random((3,3))
print(X)

[[0.91892387 0.17728449 0.45207304]
 [0.5485168  0.99303936 0.94158045]
 [0.6226196  0.29538197 0.56285585]]


In [20]:
#随机值为整数
Y=np.random.randint(4,15,size=(3,2))
print(Y)

[[12  8]
 [ 4  4]
 [ 4 11]]


random模块还有其他函数得出特殊的随机数组。

__3、访问、修改、删除、保存数组中的元素__

__①访问：索引与切片__

__⑴一般索引和切片__

选择单元素或者连续的数组子集可使用一般的索引和切片。返回的都是原数组的视图，想要拷贝数据使用方法.copy()。

切片可以和索引混合使用，切片不降维度，一个索引降一维。

In [39]:
arr2d=np.array([[1,2,3],[4,5,6],[7,8,9]])
S=arr2d[0,2]#和arr2d[0][2]的结果是一样的,表示第1行第3列的元素，只有单元素能这样写，选取多元素时使用两个方括号时别有它意，表示两次从头索引，所以可以统一起来都使用一个方括号
s=arr2d[1:2][:2]
X=arr2d[1:2,:2]
Y=arr2d[1,:2]
print(arr2d)
print(S)
print(s)
print(X)
print(Y)


[[1 2 3]
 [4 5 6]
 [7 8 9]]
3
[[4 5 6]]
[[4 5]]
[4 5]


__⑵布尔索引__

即使用布尔条件语句来选择数组的子集，当对多个布尔条件进行联合时可使用操作符&（和）、|（或）（不是使用and、or），用！=和~取反。使用布尔索引选择数据时，总是生成数据的拷贝而不是视图。

对布尔索引有两种用法：a.直接使用；b.利用布尔值False、True间接使用。

a.

In [17]:
import numpy as np
X=np.arange(25).reshape(5,5)
print(X)
print(X[X>10])#其实这也是间接使用
print(X>10)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
[11 12 13 14 15 16 17 18 19 20 21 22 23 24]
[[False False False False False]
 [False False False False False]
 [False  True  True  True  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]]


In [13]:
names=np.array(['Bob','Joe','Will','Bob','Will','Joe','Joe'])
data=np.random.randn(7,4)#布尔数组的长度必须和数组轴索引长度一致
print(names)
print(data)
print(names=='Bob')
data[names=='Bob']

['Bob' 'Joe' 'Will' 'Bob' 'Will' 'Joe' 'Joe']
[[-1.83812418  0.06659051  1.0573094   0.73185221]
 [ 2.39670262  1.33284978  1.95920204 -0.37642212]
 [ 2.05375369 -1.72410414 -0.20653792 -0.57926122]
 [ 0.14612046  0.7867952  -0.35292745  0.38884894]
 [-1.95355541 -0.76828396 -1.12681573 -1.0099884 ]
 [ 1.37831545  1.42198199 -1.33659826 -2.72602055]
 [ 0.06319191 -1.71303904  0.2299638  -1.48076606]]
[ True False False  True False False False]


array([[-1.83812418,  0.06659051,  1.0573094 ,  0.73185221],
       [ 0.14612046,  0.7867952 , -0.35292745,  0.38884894]])

__⑶神奇索引__

跳跃式取子集时可使用神奇索引，即使用整数数组进行数据索引。

In [22]:
arr=np.arange(32).reshape((8,4))
print(arr)
print(arr[[1,5,7]])
print(arr[[1,5,7],[0,3,1]])#对应索引元素
print(arr[[1,5,7]][:,[0,3,1]])#这才是行、列都跳跃索引

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]]
[[ 4  5  6  7]
 [20 21 22 23]
 [28 29 30 31]]
[ 4 23 29]
[[ 4  7  5]
 [20 23 21]
 [28 31 29]]


__⑷其他特殊访问方式__

np.diag(ndarray,k=N),取对角线上的数值，默认N=0时取主对角线；N>0的值，取在对角线上的第N个对角线的元素；N<0的值取反。

np.unique(ndarray)函数查找ndarray中的唯一元素，返回给定ndarray中的唯一值（去重后的元素）。

**②修改、删除和保存**

通过索引**修改**ndarray中的元素：

In [4]:
import numpy as np
X=np.arange(20).reshape((4,5))
print(X)
X[3]=20
print(X)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [20 20 20 20 20]]


通过np.append(ndarray,elements,axis)函数向ndarray后方**添加**数值，axis=0表示行，axis=1表示列：

In [5]:
X=np.append(X,[[0],[2],[4],[6]],axis=1)
print(X)

[[ 0  1  2  3  4  0]
 [ 5  6  7  8  9  2]
 [10 11 12 13 14  4]
 [20 20 20 20 20  6]]


In [6]:
X=np.append(X,[[1,1,1,1,1,1]],axis=0)
print(X)

[[ 0  1  2  3  4  0]
 [ 5  6  7  8  9  2]
 [10 11 12 13 14  4]
 [20 20 20 20 20  6]
 [ 1  1  1  1  1  1]]


In [7]:
X=np.append(X,[100,100])
print(X)

[  0   1   2   3   4   0   5   6   7   8   9   2  10  11  12  13  14   4
  20  20  20  20  20   6   1   1   1   1   1   1 100 100]


使用np.insert(ndarray,index,elements,axis)函数**插入**值

In [8]:
X=np.insert(X,2,[100,100])
print(X)

[  0   1 100 100   2   3   4   0   5   6   7   8   9   2  10  11  12  13
  14   4  20  20  20  20  20   6   1   1   1   1   1   1 100 100]


使用np.vstack()函数对ndarray进行垂直堆叠，使用np.hstack()函数进行水平**堆叠**（形状必须相符）。

In [10]:
X=np.array([1,2])
Y=np.array([[3,4],[5,6]])
print(X)
print(Y)
Z=np.vstack((X,Y))
W=np.hstack((Y,X.reshape(2,1)))
print(Z)
print(W)

[1 2]
[[3 4]
 [5 6]]
[[1 2]
 [3 4]
 [5 6]]
[[3 4 1]
 [5 6 2]]


使用np.delete(ndarray,elements,axis)**删除**元素

In [11]:
W=np.delete(W,[0,2],axis=1)
print(W)

[[4]
 [6]]


使用np.save(filename,ndarray)函数**保存**，使用np.load(filename.npy,ndarray)**加载**。

**4、运算**

**①集合运算**

使用np.intersectld(X,Y)取交集；使用np.setdiffld(X,Y)取差集；使用np.union(X,Y)取并集。

**②排序**

使用np.sort(ndarray,axis)函数或np.sort()方法进行排序。使用函数不会就地排序，而使用方法会。

使用sort函数和unique函数对数组中的唯一元素进行排序：```print(np.sort(np.unique(X)))```

**③算术运算和广播**

Numpy允许对ndarray执行元素级运算以及矩阵运算，这里先学习元素级运算。

在进行元素级运算时，对其执行运算的ndarray必须具有相同的形状或者**可广播**。

**⑴加减乘除**

可使用+-*/算数符号，也可使用函数np.add()、np.sbstract()、np.multiply()、np.divide()。执行结果相同，但是使用函数方式可以运用关键字选项。

**⑵数学函数**

每个函数都运算

```np.exp(X)  np.sqrt(X)  np.power(X,2)```

**⑶统计学函数**

```X.mean(axis)  X.sum(axis)  X.std(axis)  np.median(X,axis)  X.max(axis)  X.min(axis)```

**⑷使用广播功能**

指在一定条件下，可对两个形状不同的ndarray执行运算操作。

**原则**是：在对两个数组进行操作时，先写出维度（空前填后），按维度大小比较它们的形状，从尾部维度开始向前推进比较，当为以下两种条件时两个数组可称为兼容的（也就是可以进行广播）。a.它们的数字相等；b.它们的数字其中各有一个是1。

### LESSON 9 Pandas

**1、Pandas简介**

Pandas对于数据分析最重要，可以说贯穿前后，它所包含的数据结构和数据处理工具的设计使得在Python中进行数据清洗和分析非常快捷。Pandas中有两个新的重要的数据结构，Pandas Series和Pandas DateFramem，借助这两个数据结构，我们能够轻松直观地处理代表强数据和关系数据（表格）。

**2、Pandas Series**

Pandas Series是一个像数组一样的一维对象，但不同的是它可以同时储存不同类型的数据，并且可以为其中的每个元素分配自定义索引标签。

**①创建Pandas Series**

In [7]:
import pandas as pd
groceries=pd.Series(data=[30,6,'yes','no'],index=['eggs','apples','milk','bread'])
print(groceries)

eggs       30
apples      6
milk      yes
bread      no
dtype: object


**②访问、修改和删除元素**

**⑴访问**

主要通过两种方式访问：a.在[ ]内添加索引标签；b.用数字标签。可用```.loc```和```.iloc```更清晰地指代两种方式。

In [8]:
print(groceries.loc[['eggs','apples']])
print(groceries.iloc[[2,3]])

eggs      30
apples     6
dtype: object
milk     yes
bread     no
dtype: object


也可通过布尔索引进行访问,前提是里面的数据类型都可用于布尔运算。

In [15]:
print(fruits[fruits<10])

o    6
b    3
dtype: int64


分别访问索引和标签

In [10]:
print(groceries.values)
print(groceries.index)

[30 6 'yes' 'no']
Index(['eggs', 'apples', 'milk', 'bread'], dtype='object')


可用in命令检查是否存在某标签

In [11]:
X='bananas' in groceries
print(X)

False


**⑵修改**

In [12]:
groceries['eggs']=2
print(groceries)

eggs        2
apples      6
milk      yes
bread      no
dtype: object


在源数据修改

**⑶删除**

In [13]:
print(groceries.drop('eggs'))#不在源数据删
print(groceries)
print(groceries.drop('eggs',inplace=True))#在源数据删
print(groceries)

apples      6
milk      yes
bread      no
dtype: object
eggs        2
apples      6
milk      yes
bread      no
dtype: object
None
apples      6
milk      yes
bread      no
dtype: object


**③运算**

在这方面业余数组很类似。

**⑴算术运算**

先了解元素级运算中与单个数字之间的算数运算，即对所有元素都进行加减乘除。不在源数据上修改。

In [14]:
fruits=pd.Series(data=[10,6,3],index=['a','o','b'])
print(fruits)
print(fruits+2)
print(fruits)

a    10
o     6
b     3
dtype: int64
a    12
o     8
b     5
dtype: int64
a    10
o     6
b     3
dtype: int64


**⑵应用NumPy中的数学函数**

也是对每一个元素都进行运算。不在源数据上修改。

In [18]:
print(np.exp(fruits))
print(np.sqrt(fruits))
print(np.power(fruits,2))
print(fruits)

a    22026.465795
o      403.428793
b       20.085537
dtype: float64
a    3.162278
o    2.449490
b    1.732051
dtype: float64
a    100
o     36
b      9
dtype: int64
a    10
o     6
b     3
dtype: int64


**⑶部分运算**

In [35]:
print(fruits['b']+2)
print(fruits.loc[['a','o']]/2)

5
a    5.0
o    3.0
dtype: float64


**3、Pandas DataFrame**

Pandas DataFrame是具有带标签的二维数据结构，也可以同时存储很多数据类型，类似于Excel表格。

**①创建Pandas DataFrame**

先建立字典再使用函数pd.DataFrame()

**⑴使用Pandas Series字典**

In [36]:
import pandas as pd
items={'bob':pd.Series(data=[245,25,55],index=['bike','pants','watch']),'alice':pd.Series(data=[40,110,500,45],index=['book','glasses','bike','pants'])}
shopping_carts=pd.DataFrame(items)
print(shopping_carts)

           bob  alice
bike     245.0  500.0
book       NaN   40.0
glasses    NaN  110.0
pants     25.0   45.0
watch     55.0    NaN


**⑵使用列表（数组）字典**

这种方式不能出现NaN值

In [79]:
data={'intgers':[1,2,3],'floats':[4.5,8.2,9.6]}
df=pd.DataFrame(data,index=['label1','label2','label3'])
print(df)

        intgers  floats
label1        1     4.5
label2        2     8.2
label3        3     9.6


**⑶使用Python字典列表**

In [80]:
items=[{'bikes':20,'pants':30,'watches':35},{'watches':10,'glasses':50,'bikes':15,'pants':5}]
store_items=pd.DataFrame(items,index=['store1','store2'])
print(store_items)

        bikes  pants  watches  glasses
store1     20     30       35      NaN
store2     15      5       10     50.0


**②访问、修改、删除元素**

**⑴访问**

使用列、行标签，且列标签要在前。访问行、列或单个元素。

In [81]:
print(store_items[['bikes','pants']])

        bikes  pants
store1     20     30
store2     15      5


访问多个元素时，巧用'.any()'方法。

In [84]:
X=store_items[(store_items==20).any(axis=1)][['bikes','pants']]
print(X)

        bikes  pants
store1     20     30


**⑵修改**

**a.添加列**

直接添加新列新内容

In [40]:
store_items['shirts']=[15,2]
print(store_items)

        bikes  pants  watches  glasses  shirts
store1     20     30       35      NaN      15
store2     15      5       10     50.0       2


使用算术运算符添加(利用源数据)

In [41]:
store_items['suits']=store_items['pants']+store_items['shirts']
print(store_items)

        bikes  pants  watches  glasses  shirts  suits
store1     20     30       35      NaN      15     45
store2     15      5       10     50.0       2      7


使用源数据特定行特定中的数据添加

In [42]:
store_items['new watches']=store_items['watches'][1:]
print(store_items)

        bikes  pants  watches  glasses  shirts  suits  new watches
store1     20     30       35      NaN      15     45          NaN
store2     15      5       10     50.0       2      7         10.0


**b.插入列**

In [43]:
store_items.insert(4,'shoes',[8,5])
print(store_items)

        bikes  pants  watches  glasses  shoes  shirts  suits  new watches
store1     20     30       35      NaN      8      15     45          NaN
store2     15      5       10     50.0      5       2      7         10.0


**c.添加行**

需先创建一个新的DataFrame，再将其附加到源数据上。使用‘.append()'方法，添加后列顺序会自动重新排列。

In [44]:
new_items=[{'bike':20,'pants':30,'watches':35,'glasses':4}]
new_store=pd.DataFrame(new_items,index=['store3'])
store_items=store_items.append(new_store)
print(store_items)

        bike  bikes  glasses  new watches  pants  shirts  shoes  suits  \
store1   NaN   20.0      NaN          NaN     30    15.0    8.0   45.0   
store2   NaN   15.0     50.0         10.0      5     2.0    5.0    7.0   
store3  20.0    NaN      4.0          NaN     30     NaN    NaN    NaN   

        watches  
store1       35  
store2       10  
store3       35  


**d.为行列标签改名**

In [48]:
store_items=store_items.rename(columns={'bike':'hats'})
print(store_items)
store_items=store_items.rename(index={'store3':'last store'})
print(store_items)

        hats  bikes  glasses  new watches  pants  shirts  shoes  suits  \
store1   NaN   20.0      NaN          NaN     30    15.0    8.0   45.0   
store2   NaN   15.0     50.0         10.0      5     2.0    5.0    7.0   
store3  20.0    NaN      4.0          NaN     30     NaN    NaN    NaN   

        watches  
store1       35  
store2       10  
store3       35  
            hats  bikes  glasses  new watches  pants  shirts  shoes  suits  \
store1       NaN   20.0      NaN          NaN     30    15.0    8.0   45.0   
store2       NaN   15.0     50.0         10.0      5     2.0    5.0    7.0   
last store  20.0    NaN      4.0          NaN     30     NaN    NaN    NaN   

            watches  
store1           35  
store2           10  
last store       35  


**e.把某列改成索引**

In [49]:
store_items=store_items.set_index('pants')
print(store_items)

       hats  bikes  glasses  new watches  shirts  shoes  suits  watches
pants                                                                  
30      NaN   20.0      NaN          NaN    15.0    8.0   45.0       35
5       NaN   15.0     50.0         10.0     2.0    5.0    7.0       10
30     20.0    NaN      4.0          NaN     NaN    NaN    NaN       35


**⑶删除**

'.pop'方法只允许删除列，'.drop'方法配合使用axis可用于删除行或列。

In [50]:
store_items.pop('new watches')
print(store_items)

       hats  bikes  glasses  shirts  shoes  suits  watches
pants                                                     
30      NaN   20.0      NaN    15.0    8.0   45.0       35
5       NaN   15.0     50.0     2.0    5.0    7.0       10
30     20.0    NaN      4.0     NaN    NaN    NaN       35


In [52]:
store_items=store_items.drop(['hats'],axis=1)
print(store_items)

       bikes  glasses  shirts  shoes  suits  watches
pants                                               
30      20.0      NaN    15.0    8.0   45.0       35
5       15.0     50.0     2.0    5.0    7.0       10
30       NaN      4.0     NaN    NaN    NaN       35


**③处理NaN**

**⑴发现NaN**

计算NaN的个数

In [53]:
X=store_items.isnull().sum().sum()
print(X)

5


计算每列非NaN值

In [54]:
print(store_items.count())

bikes      2
glasses    2
shirts     2
shoes      2
suits      2
watches    3
dtype: int64


**⑵处理NaN**

删除有NaN值的行或列,不会再源数据上删除，除非使用inplace=True

In [56]:
print(store_items.dropna(axis=0))
print(store_items)

       bikes  glasses  shirts  shoes  suits  watches
pants                                               
5       15.0     50.0     2.0    5.0    7.0       10
       bikes  glasses  shirts  shoes  suits  watches
pants                                               
30      20.0      NaN    15.0    8.0   45.0       35
5       15.0     50.0     2.0    5.0    7.0       10
30       NaN      4.0     NaN    NaN    NaN       35


替换NaN值，不会在源数据上修改,除非使用inplace=True

In [59]:
print(store_items.fillna(0))
print(store_items)

       bikes  glasses  shirts  shoes  suits  watches
pants                                               
30      20.0      0.0    15.0    8.0   45.0       35
5       15.0     50.0     2.0    5.0    7.0       10
30       0.0      4.0     0.0    0.0    0.0       35
       bikes  glasses  shirts  shoes  suits  watches
pants                                               
30      20.0      NaN    15.0    8.0   45.0       35
5       15.0     50.0     2.0    5.0    7.0       10
30       NaN      4.0     NaN    NaN    NaN       35


In [61]:
print(store_items.fillna(method='ffill',axis=0))#按行向前填充

       bikes  glasses  shirts  shoes  suits  watches
pants                                               
30      20.0      NaN    15.0    8.0   45.0       35
5       15.0     50.0     2.0    5.0    7.0       10
30      15.0      4.0     2.0    5.0    7.0       35


In [62]:
print(store_items.fillna(method='backfill',axis=0))#按行向后填充

       bikes  glasses  shirts  shoes  suits  watches
pants                                               
30      20.0     50.0    15.0    8.0   45.0       35
5       15.0     50.0     2.0    5.0    7.0       10
30       NaN      4.0     NaN    NaN    NaN       35


In [63]:
print(store_items.interpolate(method='linear',axis=0))#插值线性填充

       bikes  glasses  shirts  shoes  suits  watches
pants                                               
30      20.0      NaN    15.0    8.0   45.0       35
5       15.0     50.0     2.0    5.0    7.0       10
30      15.0      4.0     2.0    5.0    7.0       35


In [66]:
print(store_items.fillna(store_items.mean()))#用每一列的平均值填充

       bikes  glasses  shirts  shoes  suits  watches
pants                                               
30      20.0     27.0    15.0    8.0   45.0       35
5       15.0     50.0     2.0    5.0    7.0       10
30      17.5      4.0     8.5    6.5   26.0       35


**④数据文件**

**加载**文件并赋值给GS```GS=pd.read_csv('filename')```

**查看**文件,前N行，```GS.head(N)```；后N行，```GS.tail(N)```

**快速检查**数据中是否有NaN值，```GS.isnull.any()```

**获取文件信息**

使用```GS.describe()```或```GS['A'].describe()```(针对单列)获取每列的描述性统计信息。

使用统计学函数```GS.max()```、```GS['A'].min()```等

使用.groupby()方法给数据分组统计，以获得不同类型的信息。```data.groupby(['Year'])['Salary'].sum()```即按年份分组，求所有员工薪资的总和。